name: cytoflow-qc
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.2.0
  - statsmodels>=0.14.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pyyaml>=6.0
  - jinja2>=3.1.0
  - umap-learn>=0.5.0
  - nbconvert>=7.0.0
  - snakemake>=7.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - ruff>=0.1.0
  - black>=23.0.0
  - pre-commit>=3.0.0
  - mypy>=1.0.0
  - pip
  - pip:
    - flowkit>=0.9.0
    - flowutils>=0.1.0
    - fcsparser>=0.2.0
    - typer>=0.9.0